/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1f1f28",
        "primary-fixed-dim": "#ddb8ff",
        "tertiary-fixed-dim": "#ddb7ff",
        "surface-container-lowest": "#0d0d16",
        "surface-container-high": "#292932",
        "inverse-on-surface": "#302f39",
        "secondary": "#4cd7f6",
        "surface-container-highest": "#34343d",
        "on-surface-variant": "#cfc2d7",
        "surface-container-low": "#1b1b23",
        "tertiary": "#ddb7ff",
        "surface-variant": "#34343d",
        "on-error": "#690005",
        "on-tertiary": "#490080",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-container": "#00424e",
        "on-primary": "#490080",
        "secondary-container": "#03b5d3",
        "inverse-surface": "#e4e1ed",
        "surface": "#13131b",
        "secondary-fixed": "#acedff",
        "on-primary-fixed": "#2c0051",
        "tertiary-container": "#913bdf",
        "surface-bright": "#393842",
        "on-tertiary-container": "#f6e6ff",
        "primary-fixed": "#f0dbff",
        "primary-container": "#9333ea",
        "error-container": "#93000a",
        "on-primary-container": "#f6e6ff",
        "surface-tint": "#ddb8ff",
        "inverse-primary": "#861fdd",
        "on-primary-fixed-variant": "#6800b4",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary": "#003640",
        "outline": "#988ca0",
        "on-tertiary-fixed": "#2c0051",
        "surface-dim": "#13131b",
        "primary": "#ddb8ff",
        "outline-variant": "#4d4354",
        "on-tertiary-fixed-variant": "#6900b3",
        "error": "#ffb4ab",
        "on-background": "#e4e1ed",
        "on-error-container": "#ffdad6",
        "background": "#13131b",
        "on-surface": "#e4e1ed",
        "tertiary-fixed": "#f0dbff",
        "on-secondary-fixed": "#001f26"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "element-gap": "16px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
        "unit": "8px"
      },
      fontFamily: {
        "headline-lg": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "display-xl": ["Sora", "sans-serif"],
        "serif-human": ["Playfair Display", "serif"]
      }
    },
  },
  plugins: [],
}
